[package]
name = "fuzzydate"
description = "A flexible date parsing library"
version = "0.1.5"
edition = "2021"
authors = ["Devin Vander Stelt"]
keywords = ["date", "time", "parse", "fuzzy", "string"]
categories = [
    "accessibility",
    "date-and-time",
    "parser-implementations",
    "text-processing",
]
license = "MIT"
repository = "https://github.com/DevinVS/fuzzydate"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
lazy_static = "1.4"
thiserror = "1.0"
